### ISSUE TITLE
No apply default_tags to all metrics

### ISSUE THREAD

**Issue by Javirln** [yabeda-rb/yabeda#16]
Hi,

Just wanted to ask if it was possible to add default tags only to specific metrics and not all.
In my use case I have set up a default tag that's currently being applied to all metrics exported by `yabeda-rails` but, there are other metrics where I don't want that tag to appear, is it possible to hide/not apply them?

Thanks

**Comment by Envek** [comment]
No, it is not possible as for now.

If you have any ideas on how API for this should look like, feel free to share your thoughts!

I will think about it, so will keep this issue open.

**Comment by asusikov** [comment]
What about this?

```ruby
Yabeda.configure do
  default_tag :rails_environment, 'production', group: :your_app
end
```
